[project]
name = "macrocosmos"
version = "0.1.0"
description = "The official Python SDK for Macrocosmos"
readme = "README.md"
license = "Apache-2.0"
authors = [
{ name = "Macrocosmos", email = "support@macrocosmos.ai" },
]
requires-python = ">=3.8"
dependencies = [
    "grpcio-tools>=1.70.0",
]
