name: Checks

on: [ push, pull_request ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.10"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv pip install --group dev
        env:
          UV_SYSTEM_PYTHON: 1

      - name: Run ruff check
        run: ruff check .
        
      - name: Run ruff format
        run: ruff format . --check
